export const PARTY_COLORS = {
  PSD: '#e11d48',
  PNL: '#eab308',
  PDL: '#f97316',
  PC: '#14b8a6',
  PD: '#3b82f6',
  UDMR: '#22c55e',
  UNPR: '#2563eb',
  AUR: '#d4a017',
  'PP-DD': '#8b5cf6',
  PMP: '#a855f7',
  'PNȚCD': '#166534',
  PRM: '#7c2d12',
  USR: '#06b6d4',
  SOS: '#78350f',
  ADN: '#64748b',
  PLAN: '#94a3b8',
  ANC: '#6b7280',
  PSDI: '#9ca3af',
  PNCR: '#71717a',
  PUSL: '#0ea5e9',
  'București 2020': '#0f766e',
  'Partidul pentru Odorheiu Secuiesc': '#0f766e',
  Independent: '#64748b',
  'SOS Romania': '#78350f',
  'România Socialistă': '#b91c1c',
};

export const PARTY_TOKENS = {
  PSD: 'psd',
  PNL: 'pnl',
  PDL: 'pdl',
  PC: 'pc',
  PD: 'pd',
  UDMR: 'udmr',
  UNPR: 'unpr',
  AUR: 'aur',
  'PP-DD': 'ppdd',
  PMP: 'pmp',
  'PNȚCD': 'pntcd',
  PRM: 'prm',
  USR: 'usr',
  SOS: 'sos',
  ADN: 'adn',
  PLAN: 'plan',
  ANC: 'anc',
  PSDI: 'psdi',
  PNCR: 'pncr',
  PUSL: 'pusl',
  'București 2020': 'bucuresti-2020',
  'Partidul pentru Odorheiu Secuiesc': 'partidul-pentru-odorheiu-secuiesc',
  Independent: 'independent',
  'SOS Romania': 'sos-romania',
  'România Socialistă': 'romania-socialista',
};

export const getPartyColor = (party) => PARTY_COLORS[party] || '#94a3b8';
export const getPartyToken = (party) => PARTY_TOKENS[party] || 'other';
